jobs:
  publish:
    name: Release build and publish
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check out code
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
    - continue-on-error: true
      env:
        GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
        SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
      name: Create GPG file
      run: 'git fetch --unshallow

        sudo bash -c "echo ''$GPG_KEY_CONTENTS'' | base64 -d > ''$SIGNING_SECRET_KEY_RING_FILE''"

        '
    - continue-on-error: true
      name: Release build
      run: ./gradlew :vertical-stepper-form:assembleRelease
    - continue-on-error: true
      name: Get artifacts
      run: ./gradlew androidSourcesJar javadocJar
    - continue-on-error: true
      env:
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
        SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
      name: Publish to MavenCentral
      run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1
        closeAndReleaseSonatypeStagingRepository
name: Publish
on:
  repository_dispatch:
    types: trigger-ga___publish.yml
